# Generated by Django 2.0.7 on 2018-07-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_langua'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Langua',
            new_name='Language',
        ),
    ]
